-- 코드를 입력하세요
SELECT FI.FLAVOR 
FROM FIRST_HALF FI 
LEFT OUTER JOIN ICECREAM_INFO IC
ON FI.FLAVOR = IC.FLAVOR
WHERE FI.TOTAL_ORDER > 3000 AND IC.INGREDIENT_TYPE = 'fruit_based'
ORDER BY TOTAL_ORDER DESC;
