-- 코드를 입력하세요
SELECT A.APNT_NO,P.PT_NAME, A.PT_NO,A.MCDP_CD,D.DR_NAME,A.APNT_YMD
FROM APPOINTMENT A
INNER JOIN PATIENT P
INNER JOIN DOCTOR D
ON A.PT_NO = P.PT_NO AND D.DR_ID = A.MDDR_ID
WHERE A.MCDP_CD = 'CS' AND A.APNT_YMD LIKE '%22-04-13%' AND A.APNT_CNCL_YN = 'N'
GROUP BY PT_NAME 
ORDER BY A.APNT_YMD ASC
